# cat docker-compose.yml 
version: '3'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER}/data/timescaledb:/var/lib/postgresql/data
